### PR TITLE
Fix/refactor-clean-debug

### LINKED ISSUE #29: Cypress Testing - Main Page
- [ ] Test each functioning piece of the main page for the user
- [ ] error codes are tested for main page
- [ ] Files for user Flows
 - [ ] URL pathways are tested
- [ ] Async functions are stubbed

### PR DESCRIPTION
**Pull request by battan40**
### Is this a fix or a feature?
- fix

### What is the change or fix?
- Allows full functionality of the search bar
- Reinforces separate component file modularity
- Cleans data in utils file and imports cleaning functions across components
- Refactors for DRY use cases of javaScript
- Removes functions from returns and places them in a Utils folder
- Moves all API calls to a Utils folder
- Organizes data flow at top of files in order of need
- Removes unused Routes
- Removes unneeded click-handling
- Verifies that cypress tests continue to pass with `true green` passes

### How should this be tested?
- run npm start on project folder branch
- change view for broken CSS
- Check for data about the movie not populating
- As a user use the search bar to attempt to break the app

### Linked Issues: 
- closes #29 #31 #33 #35

### CODE REVIEW

File: src/Components/Details/ShowDetails.js [hunk 1]
```diff
@@ -1,6 +1,7 @@
 import React, { Component } from 'react';
-import { fetchSingleMovie } from '../../APICalls';
 import { NavLink } from 'react-router-dom';
+import { fetchSingleMovie } from '../../Utils/APICalls';
+import { taintedAverage, cleanSingleMovieData } from '../../Utils/Utils';
```
Comment (EllieAzaveda) [inline src/Components/Details/ShowDetails.js:4]: Thanks for adding this!

File: src/Components/SearchBar/SearchBar.js [hunk 2]
```diff
@@ -1,26 +1,21 @@
...
         searchInput: '',
         error: ''
       }
   }
 
   handleChange = (event) => {
-    event.preventDefault();
     let searchValue = (event.target.value).toUpperCase();
     this.setState({ searchInput: searchValue })
+    this.props.moviesForSearchBar(this.state.searchInput)
```
Comment (EllieAzaveda) [inline src/Components/SearchBar/SearchBar.js:16]: I'm so glad we figured this out!

File: src/Utils/Utils.js [hunk 3]
```diff
@@ -0,0 +1,21 @@
...
+    return {
+      "id": movie.id,
+      "poster_path": movie.poster_path,
+      "title": movie.title,
+      "average_rating": movie.average_rating
+    }
+  })
+}
+
+export const cleanSingleMovieData = (singleMovieData) => {
```
Comment (EllieAzaveda) [inline src/Utils/Utils.js:17]: I like this conditional

File: src/Utils/Utils.js [hunk 4]
```diff
@@ -0,0 +1,21 @@
+export const taintedAverage = (movieRating) => {
+  const taintedRating = '⭐️'
+  return taintedRating.repeat(Math.floor(movieRating))
+}
+
+export const cleanAllMoviesData = (allMovies) => {
```
Comment (EllieAzaveda) [inline src/Utils/Utils.js:6]: Glad the map worked here! Thanks for cleaning this

**Review by EllieAzaveda — APPROVED** [review]

**Comment by EllieAzaveda** [comment]
Great job!
